name: 'PipeRider CLI Action'

description: 'Run the PipeRider Data Testing via GitHub Action'

author: 'InfuseAI'

branding:
  icon: 'trending-up'
  color: 'orange'

inputs: 
  stages:
    description: 'Input the path of stages yaml files, Example: stages/local.yaml or stages/*.yaml'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.stages }}
