name: 'PipeRider CLI Action'

description: 'Run the PipeRider Data Testing via GitHub Action'

author: 'InfuseAI'

branding:
  icon: 'trending-up'
  color: 'orange'

inputs: 
  stages:
    description: 'Input the file path of stages'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.stages }}
    - ${{ inputs.keep_ge_workspace }}
