name: 'PipeRider CLI Action'

description: 'Run the PipeRider Data Testing via GitHub Action'

author: 'InfuseAI'

branding:
  icon: 'trending-up'
  color: 'orange'

inputs: 
  github_token: 
    description: 'GITHUB_TOKEN or a repo scoped PAT.'
    default: ${{ github.token }}
    required: true

outputs:
  analysis:
    description: 'The analysis from PipeRider'
  status:
    description: 'The exit status from PipeRider'

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    GITHUB_TOKEN: ${{ inputs.github_token }}
